import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

// Import Images
import nuitEtoile from '../images/nuit-etoile.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="billeterie">
        <h1 className="display2 billeterie-head">Plus qu’une étape avant de rejoindre l’expérience...</h1>
        <div className="billeterie__content">
          <div className="billeterie__left">
            <Image draggable="false" src={nuitEtoile} alt="" width="200" height="200" />
          </div>
        </div>
      </main>
    </>
  )
}
