import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

// import Components
import Button from '../components/button'
import BannerTop from '../components/banner_top'

// import Images
import nuitEtoile from '../images/tableaux/nuitEtoile.webp'
import appVR from '../images/app.webp'


export default function Home() {
  return (
    <>
      <Head>
        <title>Découvrez • Une Journée Impressionnante</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="16x16" href="../images/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="../images/favicon/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="../images/favicon/favicon-32x32.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </Head>
      <main>
        <BannerTop name="Une Journée Impressionnante" image={nuitEtoile} />
        <section className="discover_infos">
          <div className="discover_infos_left">
            <h2>Présentation du Projet</h2>
          </div>
          <div className="discover_infos_right">
            <p>
            Bienvenue chez World Wide Museum ! Nous sommes une agence web composée de 6 professionnels passionnés par la création d’expositions interactives. Avec une équipe équilibrée de 3 développeurs et 3 créatifs, nous sommes prêts à vous offrir une expérience inoubliable pour vos expositions sur un thème donné. <br /> <br />
            </p>
            <p>
            Notre objectif est de fournir des solutions innovantes aux professionnels du monde des musées et des expositions qui souhaitent intégrer les nouvelles technologies à leur travail. Nous croyons que les expositions interactives sont la prochaine étape de l’industrie des musées, et nous sommes prêts à vous aider à en faire une réalité.
            </p>
            <p>
              Une Journée Impressionnante est une de nos expositions et se déroule du 10 Mars au 10 Avril.<br /> 
              Cette exposition est sur le thème de l’impressionnisme et propose à ses visiteurs une expérience unique et immersive tout au long d’une journée à travers les différents tableaux.
            </p>
          </div>
        </section>

        <section className="discover_univers">
          <h2>Notre univers</h2>
          <div className="discover_univers_contenu">
            <div className="discover_univers_contenu_left">
              <h3>La naissance de l’idée</h3>
              <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
              <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
            </div>
            <div className="discovers_univers_contenu_right">
              <h3>Notre univers</h3>
              <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
              <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
            </div>
          </div>
        </section>

        <section className="discover_app">
          <div className="discover_app_left">
            <Image draggable="false" src={appVR} alt="" width="auto" height="auto" />
          </div>
          <div className="discover_app_right">
            <h2>Application</h2>
            <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
            <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. t quia repellat aut mollitia neque aut accusamus ullam sit voluptas.</p>
            <Button linkBtn="/">DECOUVRIR</Button>
          </div>
        </section>
      </main>
    </>
  )
}
