import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

// import styles
import styles from '@/styles/Home.module.css'


// import Components
import Button from '../components/button'


// import Images
import nuitEtoile from '../images/nuit-etoile.jpg'
import pontNeuf from '../images/pont-neuf.jpg'
import soleilLevant from '../images/soleil-levant.jpg'
import navHero from '../images/hero/nav__hero.png'
import radialHero from '../images/hero/radial__hero.png'

//import icons
import arrow from '../images/icons/arrow_white.svg'


export default function Home() {

  const [peintures, setPeintures] = useState([])

  const fetchPeintures = async () => {
    fetch('https://benadjal.butmmi.o2switch.site/api_resa_expo/tableaux').then((response) => {
      return response.json()
    }).then((data) => {
      setPeintures(data)
    })
  }

  useEffect(() => {
    fetchPeintures()
  }, [])

  useEffect(() => {
    // Slider
    const gap = 32;

    const carouselContainer = document.querySelector(
      ".home__slider__container"
    );
    const carousel = document.querySelector(".home__slider");
    const next = document.querySelector(".home__slider__btn--right");
    const prev = document.querySelector(".home__slider__btn--left");

    next.addEventListener("click", (e) => {
      carouselContainer.scrollBy(width + gap, 0);
    });
    prev.addEventListener("click", (e) => {
      carouselContainer.scrollBy(-(width + gap), 0);
    });

    carouselContainer.addEventListener("scroll", () => {
      if (carouselContainer.scrollLeft != 0) {
        prev.disabled = false;
      } else {
        prev.disabled = true;
      }

      if (
        carouselContainer.offsetWidth + carouselContainer.scrollLeft >=
        carouselContainer.scrollWidth
      ) {
        next.disabled = true;
      } else {
        next.disabled = false;
      }
    });

    let width = carouselContainer.offsetWidth;
    window.addEventListener(
      "resize",
      (e) => (width = carouselContainer.offsetWidth)
    );
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="color-scheme" content="dark"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='hero'>
          <div className='hero-top'>
            <span className='display3'>Visite interactive</span>
            <span className='spacer'></span>
            <span className='display3'>Compatible casque VR</span>
          </div>
          <h1>Entrez au coeur de limpressionnisme</h1>
          <Button name="Rejoindre lexpérience" linkbtn="/billeterie"></Button>
          <Image className="hero__bg" draggable="false" src={nuitEtoile} alt="" width="auto" height="auto" />
          <Image className="nav__hero" draggable="false" src={navHero} alt="" width="auto" height="auto" />
          <Image className="radial__hero" draggable="false" src={radialHero} alt="" width="auto" height="auto" />
        </section>
        <section className='home_infos'>
          <div className="home_infos_left">
            <h2>VISITEZ LE WORLD WIDE MUSEUM</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro explicabo voluptatem qui atque quam quaerat consequatur blanditiis hic vitae aperiam corporis provident, quo eum ullam veritatis eligendi eaque ex tempora placeat, unde, omnis maiores modi repudiandae quia. Similique, inventore incidunt in facilis nemo commodi suscipit fuga ipsum tempora excepturi ipsam omnis a aperiam? Laudantium numquam ad omnis officia ipsa magni debitis hic velit itaque corrupti cum, non unde adipisci nostrum maxime perspiciatis aliquid similique, dolorum officiis maiores inventore minima autem? Velit illum at maiores sed accusantium dolorum voluptate unde possimus quo magni commodi animi doloremque distinctio reiciendis, obcaecati magnam. Sint?</p>
          </div>
          <div className='home_infos_right'>
            <Image draggable="false" src={nuitEtoile} alt="" width="auto" height="auto" className="nuitEtoile" />
            <Image draggable="false" src={pontNeuf} alt="" width="auto" height="auto" className="pontNeuf" />
            <Image draggable="false" src={soleilLevant} alt="" width="auto" height="auto" className="soleilLevant" />
          </div>
        </section>
        <section className="home_oeuvres">
          <h2>DÉCOUVRIR LES OEUVRES</h2>
          <div className="home__slider__wrapper">
            <div className="home__slider__container">
              <div className="home__slider">
                {
                  peintures.map((peinture) => {
                    return (
                      <>
                        <Link href={`/oeuvre?id=${peinture.id_tableau}`} key={peinture.id_tableau} className="oeuvre-card">
                          <div className="oeuvre_infos">
                            <h3 className="display2">{peinture.nom_tableau}</h3>
                            <div className="spacer"></div>
                            <p className="display3">{peinture.nom_peintre}</p>
                          </div>
                          <Image draggable="false" src={nuitEtoile} alt="" width="auto" height="auto" />
                        </Link>
                      </>
                    )
                  })
                }
              </div>

            </div>
            <div className="home__slider__btns">
              <button className="home__slider__btn--left" disabled><Image draggable="false" src={arrow} alt="" width="auto" height="auto" /></button>
              <button className="home__slider__btn--right"><Image draggable="false" src={arrow} alt="" width="auto" height="auto" /></button>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}