import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';



export default function Home() {

  const router = useRouter();

  let id = router.query.id;
  if (id === undefined) id = 1;

  const ariane = useRef(null);
  const titre = useRef(null);
  const auteur = useRef(null);
  const description = useRef(null);
  const image = useRef(null);
  const idOeuvre = useRef(null);

  const fetchOeuvre = async () => {
    await fetch('https://benadjal.butmmi.o2switch.site/api_resa_expo/tableaux/' + id)
      .then(res => res.json())
      .then(data => {
        //si un id est renseigné mais que l'oeuvre n'existe pas
        if (data.tableau === undefined) router.push('/404');
        titre.current.innerHTML = data.tableau.nom_tableau + ', ' + data.tableau.date_tableau;
        auteur.current.innerHTML = data.tableau.nom_peintre;
        description.current.innerHTML = data.tableau.description_tableau;
        image.current.innerHTML = '<img src="http://localhost:3000/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fpont-neuf.4d683e51.jpg&w=3840&q=10" alt="' + data.tableau.nom_tableau + '">';
        idOeuvre.current = data.tableau.id_tableau;
        ariane.current.innerHTML = data.tableau.nom_tableau

        titre.current.classList.remove('skeleton');
        auteur.current.classList.remove('skeleton');
        description.current.classList.remove('skeleton');
        image.current.classList.remove('skeleton');
      })
      .catch(err => console.log(err));
  }


  useEffect(() => {
    if (!id) return;
    fetchOeuvre();
  }, [id]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="oeuvrepage">
        <div className="oeuvrepage_ariane">
          <Link href="/">Accueil</Link>
          <span> / </span>
          <Link href="/collection">Collection</Link>
          <span> / </span>
          <Link href={"/oeuvre?id=" + id} key={idOeuvre} ref={ariane}>---</Link>
        </div>
        <section className="oeuvrepage_infos">
          <div className="oeuvrepage_infos_titre">
            <h1 ref={titre} className="skeleton"></h1>
            <h2 ref={auteur} className="skeleton"></h2>
          </div>
          <div className="oeuvrepage_infos_details">
            <div className="oeuvrepage_infos_details_image skeleton" ref={image}>
            </div>
            <div className="oeuvrepage_infos_details_txt skeleton" ref={description}>
              <p></p>
              <p></p>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}