import { useState, useEffect, useRef } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  let id = router.query.id;
  let Loading = true;
  const [oeuvre, setOeuvre] = useState({});

  const titre = useRef(null);
  const auteur = useRef(null);
  const description = useRef(null);
  const image = useRef(null);
  const idOeuvre = useRef(null);

  const fetchOeuvre = async () => {
    fetch('https://benadjal.butmmi.o2switch.site/api_resa_expo/tableaux/' + id)
      .then(res => res.json())
      .then(data => {
        setOeuvre(data);
        Loading = false;
      })
      .catch(err => console.log(err));
  }


  useEffect(() => {
    if (!id) return;
    fetchOeuvre();
  }, [id]);

  // useEffect(() => {
  //   if (oeuvre.length === 0) return;
  //   titre.current.innerHTML = oeuvre.tableau.nom_tableau;
  // }, [id]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="oeuvrepage">
        <div className="oeuvrepage_ariane">
          <Link href="/">Accueil</Link>
          <span> / </span>
          <Link href="/collection">Collection</Link>
          <span> / </span>
          <Link href={"/oeuvre/" + id} key={idOeuvre}>Nom de lOeuvre</Link>
        </div>
        <section className="oeuvrepage_infos">
          <div className="oeuvrepage_infos_titre">
            <h1 ref={titre}>NOM DE LOEUVRE, 1881</h1>
            <h2 ref={auteur}>Nom de lAuteur</h2>
          </div>
          <div className="oeuvrepage_infos_details">
            <div className="oeuvrepage_infos_details_image" ref={image}>
            </div>
            <div className="oeuvrepage_infos_details_txt" ref={description}>
              <p>Lorem ipsum dolor sit amet. Est rerum vero qui sequi nobis sed fugiat ratione. Et quia repellat aut mollitia neque aut accusamus ullam sit voluptas distinctio non accusantium dolor qui perferendis dolorem ea sint nihil.</p>
              <p>Eos incidunt placeat est aliquam sapiente quo ullam enim est animi minima ut deleniti voluptatem est vitae galisum non maxime omnis. Ut nostrum repellat sit nobis quia est adipisci voluptatem ab maiores eligendi aut molestiae reiciendis in atque quaerat quo omnis velit!</p>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}