import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  let id = router.query.id;
  const [oeuvre, setOeuvre] = useState({});

  const fetchOeuvre = async () => {
    fetch('https://benadjal.butmmi.o2switch.site/api_resa_expo/tableaux/' + id)
      .then(res => res.json())
      .then(data => {
        setOeuvre(data);
        console.log(data);
      })
      .catch(err => console.log(err));
  }

  //attendre qu'on ait le id
  useEffect(() => {
    if (!id) return;
    fetchOeuvre();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Oeuvre</h1>
      </main>
    </>
  )
}